=== Yaamiilaa/LND/XML/Ejercicio UT705.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT libreria (libro*)>
<!ELEMENT libro (nombre,nombre-autor,apellido-autor+,editorial,email-autor?, direccion )>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nombre-autor (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT email-autor (#PCDATA)>

<!ELEMENT direccion (calle, numero, cp)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT cp (#PCDATA)>

<!ATTLIST editorial pais CDATA #REQUIRED >

=== Yaamiilaa/LND/XML/Ejercicio UT705.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria SYSTEM "Ejercicio UT705.dtd">
<libreria>
	<libro>
		<nombre>Al final mueren los dos</nombre>
		<nombre-autor>Adam</nombre-autor>
		<apellido>Silvera</apellido>
		<apellido>Hernandez</apellido>
		<editorial pais="España">PUCK</editorial>
		<email-autor>Adam.Sil.Hdez@gmail.com</email-autor>
		<direccion>
			<calle>C/ Don Nicolás el Médico</calle>
			<numero>4</numero>
			<cp>38480</cp>
		</direccion>
	</libro>
</libreria>
